# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e5c72ed6212fb6fe6052575253ad91ff87319b8e89c19b223562471cd1b7835e80cd8431303b12c88c14f79c271dae5def0724f48665d32004cbc6ef3cbe626

test:
  secret_key_base: b2849e7a1036b75282739ac7a7384d4bcae96a717fa916ec540706fb927ca5c4a1506807e222e30cd11e70519f3acbe7dd0058db3cbb0ba1bfb59713dc8ca6cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
